name: Build and Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:    
  buildAndDeploy:

    env:
      CLOUDHUB_ID: ${{ secrets.ANYPOINT_PLATFORM_USERNAME}}
      CLOUDHUB_SECRET: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD}}
      CLOUDHUB_ENVIRONMENT: "Sandbox" 
      CLOUDHUB_WORKERS: "1"
      CLOUDHUB_WORKER_TYPE: "MICRO"
      CLOUDHUB_REGION: "us-east-2"

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2       

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
            
   
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17

# Deploy to CloudHub
    - name: Deploy             
      run: |
        mvn deploy -DmuleDeploy \
        -Danypoint.username=${{ env.CLOUDHUB_ID}} \
        -Danypoint.password=${{ env.CLOUDHUB_SECRET}} \
        -Dcloudhub.environment=${{ env.CLOUDHUB_ENVIRONMENT}} \
        -Dcloudhub.workerType=${{ env.CLOUDHUB_WORKER_TYPE}} \
        -Dcloudhub.workers=${{ env.CLOUDHUB_WORKERS}} \
        -Dcloudhub.region=${{ env.CLOUDHUB_REGION}} \
      


      


    